name: Lint and Test App

on: push

jobs:
  lint:
    name: Lint and Test App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false

      - name: Run go get
        run: go get

      # Install rpi-rgb-led-matrix
      - name: Install rpi-rgb-led-matrix
        run: |
          git clone https://github.com/hzeller/rpi-rgb-led-matrix.git
          cd rpi-rgb-led-matrix
          make -j

      - name: Run go fmt
        run: test -z $(gofmt -l .)

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          args: --out-format=colored-line-number

      - name: Run go vet
        run: go vet -all ./...

      - name: Test app
        run: go test ./...
